### ISSUE TITLE
Unfortunately, update 1.7.3 does not fix the problem that I described in article #440.(((

### ISSUE THREAD

**Issue by Pehotinec78** [MAFINS/MenyooSP#449] opened 2022-12-23 16:24 UTC

**Comment by itsjustcurtis** [comment] 2022-12-23 16:38
Please don't open a new issue when one already exists.

**Comment by metoxys** [comment] 2022-12-24 12:20
Duplicate of #440 
Please close this @MAFINS

**Closed** 2022-12-24 15:52 UTC
