### ISSUE TITLE
Cars despawning when spawned using Menyoo

### ISSUE THREAD

**Issue by Alyxiate** [MAFINS/MenyooSP#427] opened 2022-11-22 06:07 UTC
whenever i attempt to use menyoo to spawn a car it immediately despawns upon driving away

**Comment by mistahwolf** [comment] 2022-11-24 01:24
Have you used the 'make personal vehicle' option or immediately upon spawning select 'make entity part of database?' I don't use the first one because the name of the vehicle 'follows you' anywhere you are. The second is much better, but there is no 'blip' on the map for it. However, if you go into the database you can bring it to you or teleport to where it is.

**Comment by The-UnXplained** [comment] 2022-11-25 19:19
The version on here is not actually fully up-to-date and hasn't been for some time now..

**Comment by itsjustcurtis** [comment] 2022-11-29 13:56
> 

This is categorically untrue. The release dates very quickly disprove that. 

@Alyxiate is it any specific vehicles that you are having this issue with? There are controls in place that should prevent this behaviour, so I would be interested to see what is allowing them to despawn.

**Comment by The-UnXplained** [comment] 2022-11-29 17:35
If its dlc vehicles that are despawning then its because GTAmemory.cpp hasn't been updated..

void GeneralGlobalHax::EnableBlockedMpVehiclesInSp(bool uSure)
{
switch (GTAmemory::GetGameVersion())
	{ case eGameVersion::VER_1_0_2699_0_NOSTEAM: case eGameVersion::VER_1_0_2699_0_STEAM:
		*GTAmemory::GetGlobalPtr<INT32>(4533757) = uSure ? 1 : 0; break;
	}

Last updated 4 months ago lol.

-------------------------------------------------------
Why people keep using this crappy, messed about with, screwed up, outdated version on here is beyond me..

**Comment by itsjustcurtis** [comment] 2022-11-29 17:43
2699 came out in July? Of course it was last updated 4 months ago lol. 2699.16 didn't modify any critical functions so _shouldn't_ affect it, but I'm happy to look into it. 

If its crappy and outdated then why not contribute yourself? MAFINS has clearly said they don't have time to do it anymore, hence making it open source. Why not help us make it better?

**Comment by The-UnXplained** [comment] 2022-11-30 00:19
> why not contribute yourself? MAFINS has clearly said they don't have time to do it anymore, hence making it open source. Why not help us make it better?

Let me explain something to you: when MAFINS stopped updating this menu on the 5mods website around 2019 i contacted him and asked if it was ok with him if i took it over and kept it updated.. he told me he was done with it and to do what i liked with it.. when i did just that, and submitted it to the 5mods site for approval he decided to change his mind, got his little moderator friends on there to ban me. A few days later, he decides to allow pull request on here. In my opinion, this was done so he can sit on his backside while letting others do all the hard work and then lets everyone falsely continue to believ he updates it when 99% of the time he doesn't update anything.  The fact is this menu would be of been dead years ago if it wasn't for the few contributors.

The guy now suffers from memory loss it seem's and will no doubt be along shortly to claim i'm spreading slander and misinformation but you only have to look back at all the comments on the 5mods site in 2019 that his friends forgot to delete to work out for yourself whos telling the truth here.. In closing, i still update this menu for those who still want it (link to it on my profile) but i will never become one of his puppets and update it via pull request on here!

**Comment by The-UnXplained** [comment] 2022-11-30 00:38
If you or any of the other contributors want my advice, i recommend you do what i never got around to doing, create your own repository, remake the menu into a better base and call it something else.. like 'RampageDev' did.

**Comment by mistahwolf** [comment] 2022-11-30 12:50
The-UnXplained, I was having problems with one of your versions before this latest one. I couldn't load large maps anymore and later the teleports are jacked by only allowing to enter maps in a vehicle. Looks like your latest version came out a day after 1.7.2. Did you get around to addressing these and the aforementioned issues?

**Comment by The-UnXplained** [comment] 2022-11-30 16:48
Just to be clear, (to all) my version is not to be confused with any versions that are released on here. My latest version that was released on 15-11-2022  requires you to be using the latest game version (v1.0.2699.16) - everything apart from the offset's for "DisableAnnoyingRecordingUI" has been fully updated so everything apart from that should be working as intended..

----------------------------------------------------------------------------
I'm currently working on merging 3 version's of this menu (mafins, mine and someone else's) into one and will consider uploading it to my profile once completed so everyone can contact me on there should there be any issues.

**Comment by Clone69420** [comment] 2022-11-30 17:09
> 

New SP Despawn Bypass Global '4539659'

**Comment by metoxys** [comment] 2022-12-18 15:47
Unfortunately having the same issue

**Comment by itsjustcurtis** [comment] 2022-12-18 16:05
> > 
> 
> New SP Despawn Bypass Global '4539659'

Where to you find these globals? I've tried hunting for them to no avail. I want to make sure that the global is updated correctly.

**Comment by metoxys** [comment] 2022-12-18 17:04
New global should be 4540726 @MAFINS

**Comment by metoxys** [comment] 2022-12-18 17:53
> Where to you find these globals? I've tried hunting for them to no avail. I want to make sure that the global is updated correctly.

See https://www.unknowncheats.me/forum/3632133-post14075.html and the thread

**Comment by metoxys** [comment] 2022-12-18 18:10
> Where to you find these globals? I've tried hunting for them to no avail. I want to make sure that the global is updated correctly.

@itsjustcurtis See https://www.unknowncheats.me/forum/3632133-post14075.html and the thread

**Comment by The-UnXplained** [comment] 2022-12-19 20:35
I tried 4540726 on my version and it isn't working for some reason..

**Comment by metoxys** [comment] 2022-12-19 20:41
> I tried 4540726 on my version of menyoo and it isn't working for some reason..

Strange. Earlier today, [Rampage Trainer](https://www.gta5-mods.com/scripts/rampage-trainer) got updated and I'm loading that in addition to Menyoo to bypass the despawn

**Comment by The-UnXplained** [comment] 2022-12-19 21:01
That is strange,  because as i'm sure you already know that menu is basically menyoo built into a new base.. - i have even checked that global myself in the decompiled scripts to make sure it was correct.

**Comment by metoxys** [comment] 2022-12-19 21:11
> That is strange, because as i'm sure you already know that menu is basically menyoo built into a new base.. - i have even checked that global myself in the decompiled scripts to make sure it was correct.

Nope, never heard of Rampage Trainer in my life before today. I kept refreshing gta5mods sorted by latest version because I was impatient to test drive dripfeed vehicles

**Comment by itsjustcurtis** [comment] 2022-12-19 23:46
I've just tried the native above and its not working here either. Saw that Unxplained posted in the forum. I'll keep an eye out if anything comes up

**Comment by Alyxiate** [comment] 2022-12-20 16:34
Welp, it's got even worse with latest update, no fix currently, tempted to just revert back to previous update until it's fully fixed

**Comment by Alyxiate** [comment] 2022-12-20 16:40
> Welp, it's got even worse with latest update, no fix currently, tempted to just revert back to previous update until it's fully fixed

Nvm, rampage menu fixed it

**Comment by itsjustcurtis** [comment] 2022-12-20 16:56
Am aware that Rampage fixes the issue, though would like to understand how so the same can be applied here. Would rather not force people to use multiple trainers just to get access to certain functionality

**Comment by Alyxiate** [comment] 2022-12-20 16:59
> Am aware that Rampage fixes the issue, though would like to understand how so the same can be applied here. Would rather not force people to use multiple trainers just to get access to certain functionality

Probably best to ask whoever keeps rampage updated with that, as it seems so far that's the only menu I've seen that fixes it

**Closed** 2022-12-23 12:35 UTC
