### ISSUE TITLE
menyo cars despawning when spawned in the latest update ( only new ones orginal ones from singleplayer work ) 

### ISSUE THREAD

**Issue by Asbbester** [MAFINS/MenyooSP#441] opened 2022-12-19 16:59 UTC
i am having some trouble with spawning DLC cars from online version
i tried:
installing simple trainer ( x2 times one without scripts folder and one with )
downloading the premium auto dealership
downloading script hook community edition
If someone can help me i would be very greatfull for that
(sorry for some incorect english i am from poland and i am having trouble with english )

**Comment by metoxys** [comment] 2022-12-19 18:01
Same issue as #427...

**Comment by WithLithum** [comment] 2022-12-20 03:48
If you mean GTA Online DLC vehicles are despawned, that is due to Rockstar intentionally doing it and this needs to be patched for each game update.

**Comment by The-UnXplained** [comment] 2022-12-20 16:26
Some of us are aware of this issue and are currently trying to fix it. The problem is, the new "Global" we have (4540726) from the latest decompiled scripts to 'Enable Blocked Mp Vehicles In Single Player' isn't working for some reason..

**Comment by Alyxiate** [comment] 2022-12-20 16:27
Yup, I had this issue #427 and I originally fixed it with simple trainer but since this new update everything has fucked up, tried simple trainer, nothing, can't even try the recommendations people put in my issue and that doesn't even work as cars are despawning faster than I can get to the other settings

**Comment by Alyxiate** [comment] 2022-12-20 16:42
> i am having some trouble with spawning DLC cars from online version i tried: installing simple trainer ( x2 times one without scripts folder and one with ) downloading the premium auto dealership downloading script hook community edition If someone can help me i would be very greatfull for that (sorry for some incorect english i am from poland and i am having trouble with english )

Use rampage menu, it fixes the despawn, and you can continue using whichever menu you want to spawn cars, personally I use add-on vehicle spawner, just make sure you have rampage installed

**Comment by AlexDD10** [comment] 2022-12-21 20:59
> > i am having some trouble with spawning DLC cars from online version i tried: installing simple trainer ( x2 times one without scripts folder and one with ) downloading the premium auto dealership downloading script hook community edition If someone can help me i would be very greatfull for that (sorry for some incorect english i am from poland and i am having trouble with english )
> 
> Use rampage menu, it fixes the despawn, and you can continue using whichever menu you want to spawn cars, personally I use add-on vehicle spawner, just make sure you have rampage installed

Finally, thanks mannn i have been all day to try make menyoo work T_T

**Comment by itsjustcurtis** [comment] 2022-12-22 15:09
> Some of us who are aware of this issue and are currently trying to fix it. The problem is, the new "Global" we have (4540726) from the latest decompiled scripts to 'Enable Blocked Mp Vehicles In Single Player' isn't working for some reason..

I can confirm that this global is working. There is likely something else in your code preventing it from properly hooking.

**Comment by metoxys** [comment] 2022-12-22 15:19
> > Some of us who are aware of this issue and are currently trying to fix it. The problem is, the new "Global" we have (4540726) from the latest decompiled scripts to 'Enable Blocked Mp Vehicles In Single Player' isn't working for some reason..
> 
> I can confirm that this global is working. There is likely something else in your code preventing it from properly hooking.

Maybe (at least it's the only thing that comes to my mind right now) it's a different global depending on Steam/RGL/EG?

**Comment by itsjustcurtis** [comment] 2022-12-22 19:28
Nope, there is no differentiation between versions since 2699.16, SHV logs confirm this. RampgeDev and Myself have both got this global working now, as have others in their own personal builds.

**Comment by metoxys** [comment] 2022-12-23 10:40
Confirmed fixed in v1.7.3

Can close this @MAFINS

**Closed** 2022-12-28 13:36 UTC
