### ISSUE TITLE
Vehicle opacity 

### ISSUE THREAD

**Issue by alyxandravance** [MAFINS/MenyooSP#413] opened 2022-10-19 17:35 UTC
All spawned vehicles will have an opacity value of 255 but will still be slightly transparent until "reset" making the vehicle properly opaque. Occurs even if opacity is already at value 255

**Comment by OmegAlex10** [comment] 2022-10-20 04:39
Most likely a menyoo bug (if it's a newer version)

**Comment by alyxandravance** [comment] 2022-10-20 04:44
Yeah I discovered this after installing the lastest version. It behaves like the value is <255 even if you manually set it to 255/100% unless you use the actual reset button

**Comment by itsjustcurtis** [comment] 2022-10-23 18:43
Can you elaborate a bit on this? I'd be interested to see if I can include a fix for this in my next update

**Comment by alyxandravance** [comment] 2022-10-23 18:46
I'll see if I can post a screenshot later

Sent from my U.S.Cellular© Smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by itsjustcurtis** [comment] 2022-10-23 19:01
I have an idea of what the cause may be having looked at the code, going to see if I can force reset when 255/100% is selected

**Closed** 2022-12-29 11:07 UTC
