### ISSUE TITLE
Problem with DLC cars.

### ISSUE THREAD

**Issue by Pavle112** [MAFINS/MenyooSP#444] opened 2022-12-21 20:34 UTC
When I create a vehicle after a few moments it kicks me out of the vehicle or deletes it. How do I fix this problem? I had this problem before but somehow it just got better.

**Comment by metoxys** [comment] 2022-12-22 10:37
Duplicate of #427

**Comment by Pavle112** [comment] 2022-12-22 13:12
Ok and how to fix?

**Comment by Pavle112** [comment] 2022-12-22 21:29
Ok thanks!

**Comment by metoxys** [comment] 2022-12-23 10:39
Confirmed fixed in v1.7.3

Can close this @MAFINS

**Closed** 2022-12-23 12:35 UTC
